
SET (CMAKE_SYSTEM_NAME Generic)
SET (CMAKE_SYSTEM_PROCESSOR ARM926EJ-S)

SET (CMAKE_C_COMPILER arm-none-eabi-gcc)
SET (CMAKE_CXX_COMPILER arm-none-eabi-g++)
SET (CMAKE_ASM_COMPILER arm-none-eabi-as)

SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
